from __future__ import annotations

from pathlib import Path

import pytest

from convgap.recipe import Recipe, RecipeKind
from convgap.registry import all_applications


@pytest.mark.parametrize("app", all_applications(), ids=lambda a: a.key)
def test_every_application_declares_a_recipe(app) -> None:
    recs = app.recipes()
    assert recs, f"{app.key}: declares no recipe"
    for rec in recs:
        assert isinstance(rec, Recipe)
        assert rec.argv, f"{app.key}: recipe has no command"
        assert rec.produces, f"{app.key}: recipe names no artifact"
        assert rec.tree in {"research", "engine", "local"}
        assert rec.est_seconds > 0


@pytest.mark.parametrize("app", all_applications(), ids=lambda a: a.key)
def test_recipe_produces_what_the_evidence_cites(app) -> None:
    """Every artifact the evidence points at is regenerated, or explained.

    The exception is a source re-derived by this repository, which has its own
    recipe under `convgap replicate` rather than a pipeline stage.
    """
    produced = {a for rec in app.recipes() for a in rec.produces}
    for half in (app.significance(), app.value()):
        for item in half.items:
            if item.source.tree == "local":
                continue  # regenerated by `convgap replicate`
            assert item.source.artifact in produced, (
                f"{app.key}: cites {item.source.artifact} but no recipe writes it"
            )


def test_python_token_resolves_to_a_tree_interpreter(tmp_path: Path) -> None:
    from convgap.provenance import SourceTree

    venv = tmp_path / ".venv" / "bin"
    venv.mkdir(parents=True)
    (venv / "python").write_text("#!/bin/sh\n")
    (venv / "python").chmod(0o755)
    trees = {"research": SourceTree("research", tmp_path, "fixture")}
    rec = Recipe(RecipeKind.PIPELINE_STAGE, "research", ["{python}", "x.py"], ["a"])
    argv = rec.resolve_argv(trees, Path("."))
    assert argv[0].endswith(".venv/bin/python"), (
        "a source tree must run under its own environment, not ours"
    )


def test_missing_venv_falls_back(tmp_path: Path) -> None:
    from convgap.provenance import SourceTree

    trees = {"research": SourceTree("research", tmp_path, "fixture")}
    rec = Recipe(RecipeKind.PIPELINE_STAGE, "research", ["{python}", "x.py"], ["a"])
    assert rec.resolve_argv(trees, Path("."))[0] == "python3"
