"""A3 - the external control: a non-flow predictor through identical machinery.

A3 is not an application of the dataset under study. It is drawn from outside
it entirely - the trailing five-day return of a foreign index - and is run
through the same screen, the same bar and the same engine construction. Its
purpose is to separate two explanations of the ladder's attrition: that the
institutional flow record in particular fails to convert, or that the
transition from statistical evidence to institutional use is where findings
generally stop. A control dying at the same level as the applications supports
the second.
"""

from __future__ import annotations

from convgap.application import Application, Layer, evidence_set
from convgap.evidence import Era, Evidence, EvidenceSet, Statistic
from convgap.extract import csv_cell, log_regex
from convgap.friction import FrictionLevel
from convgap.provenance import Source
from convgap.recipe import Recipe, RecipeKind
from convgap.registry import register
from convgap.role import Role

_LOG = "outputs/logs/20260824_231440_weekly_engine.log"
_PRODUCER = "src/fii/validation/module24_weekly_engine.py"
_SCREEN = "outputs/replication/weekly_screen.csv"


@register
class MacroRedundancy(Application):
    key = "A3"
    title = "S&P 500 -> Nifty weekly volatility spillover"
    layer = Layer.DENSITY
    role = Role.CONTROL
    fails_at = FrictionLevel.COMPETITION
    mechanism = (
        "Redundancy against an autoregressive baseline, demonstrated on a predictor "
        "drawn from outside the dataset. The spillover is among the most era-stable "
        "coefficients in the programme - same sign, comparable magnitude, and if "
        "anything stronger out of sample - and a GJR-GARCH base absorbs it entirely "
        "through the index's own lagged returns. Era-stability is evidence that an "
        "effect is real; it is not evidence that the effect is incremental. That this "
        "control dies at the same level as the flow applications is the paper's "
        "evidence that the friction belongs to the evaluation transition rather than "
        "to the record."
    )

    def recipes(self) -> tuple[Recipe, ...]:
        return (
            Recipe(
                kind=RecipeKind.PIPELINE_STAGE,
                tree="research",
                argv=["{python}", "pipeline.py", "--stage", "weekly_engine"],
                produces=[_LOG],
                est_seconds=68,
                note="Weekly GJR-5 base with an S&P tilt. The W1-W3 screen that "
                "gates it is regenerated by `convgap replicate`.",
            ),
        )

    def significance(self) -> EvidenceSet:
        def _screen(era: str) -> Source:
            return Source(
                tree="local",
                artifact=_SCREEN,
                locator=f"row cell=W3, era={era}, column t_stat",
                producer="src/convgap/replication/weekly_screen.py",
            )

        note = (
            "Re-derived here from the pre-registered specification. The source "
            "programme reports t = -3.50 / -2.72 / -4.39 in the Result section "
            "appended to its pre-registration, but has no stage that computes the "
            "screen. All three cell verdicts replicate, including the reasons the "
            "other two fail: W1 flow persistence flips sign between eras, W2 "
            "USDINR is TRAIN-only."
        )
        return evidence_set(
            "W3 screen: 5-day S&P 500 return on next-week Nifty realised volatility",
            Evidence(
                -3.86,
                Statistic.T_STAT,
                _screen("FULL"),
                era=Era.FULL,
                extractor=csv_cell({"cell": "W3", "era": "FULL"}, "t_stat"),
                note=note,
            ),
            Evidence(
                -2.91,
                Statistic.T_STAT,
                _screen("TRAIN"),
                era=Era.TRAIN,
                extractor=csv_cell({"cell": "W3", "era": "TRAIN"}, "t_stat"),
            ),
            Evidence(
                -4.46,
                Statistic.T_STAT,
                _screen("TEST"),
                era=Era.TEST,
                extractor=csv_cell({"cell": "W3", "era": "TEST"}, "t_stat"),
            ),
        )

    def value(self) -> EvidenceSet:
        def _log(locator: str) -> Source:
            return Source(tree="research", artifact=_LOG, locator=locator, producer=_PRODUCER)

        return evidence_set(
            "module 24 pre-registered gate (legs a and b FAIL)",
            Evidence(
                1.58,
                Statistic.DM_STAT,
                _log("gate leg (a): 'FULL DM t = ...', bar t <= -2.0"),
                era=Era.FULL,
                n=2210,
                extractor=log_regex(r"\(a\) FULL DM t = ([-+\d.]+)"),
                note="Positive: the tilted engine scores worse than the base.",
            ),
            Evidence(
                0.0020,
                Statistic.CRPS,
                _log("gate leg (b): mean CRPS advantage x100, TRAIN"),
                era=Era.TRAIN,
                extractor=log_regex(r"both eras better: TRAIN ([-+\d.]+)"),
            ),
            Evidence(
                0.0000,
                Statistic.CRPS,
                _log("gate leg (b): mean CRPS advantage x100, TEST"),
                era=Era.TEST,
                extractor=log_regex(r"both eras better: TRAIN [-+\d.]+ TEST ([-+\d.]+)"),
            ),
        )
