"""A8 - the survivor: the one application that clears every level.

Without a survivor the exhibit reports that the record is worthless, which is
both weaker and less falsifiable than mapping where its value stops. A8 is what
makes the ladder a boundary rather than a verdict, and it states the conditions
under which the record does pay: aggregated to market level, available at a
deployable lag, of sufficient magnitude, and scored against a baseline that has
not already absorbed it.
"""

from __future__ import annotations

from convgap.application import Application, Layer, evidence_set
from convgap.evidence import Era, Evidence, EvidenceSet, Statistic
from convgap.extract import Extractor, csv_cell, log_regex
from convgap.provenance import Source
from convgap.recipe import Recipe, RecipeKind
from convgap.registry import register
from convgap.role import Role

#: Timestamped run log from the re-execution of 2026-08-24. Timestamped logs are
#: append-only and uniquely identify a run, which makes them stronger provenance
#: than the stable-named copies the reporting stage maintains.
_LOG = "outputs/logs/20260824_223938_market_flow_engine.log"
_PRODUCER = "src/fii/validation/module21_market_flow_engine.py"

#: BLOCKED. The C1-C4 screen regression that establishes the significance half
#: has no producing stage anywhere in the pipeline; the figures survive only as
#: a docstring in the module that consumes them. See verification log V2a.
_PREREG = "docs/PREREG_AGGREGATE_FLOW.md"


def _log(locator: str) -> Source:
    return Source(tree="research", artifact=_LOG, locator=locator, producer=_PRODUCER)


def _rx(pattern: str) -> Extractor:
    return log_regex(pattern)


@register
class AggregateFlowConversion(Application):
    key = "A8"
    title = "Aggregate FII net flow -> market-level density"
    layer = Layer.DENSITY
    role = Role.APPLICATION
    fails_at = None
    mechanism = (
        "The survivor. The record aggregated to market level, entering a Student-t "
        "density at a two-day reporting lag, against an EWMA baseline that has not "
        "already absorbed it. Identical regression evidence to A2; the two differ "
        "only in the baseline the tilt is asked to improve, which is what makes the "
        "pair a controlled test of the competition level. This is also the only "
        "engine result in the programme unchanged to every printed digit under two "
        "later estimation fixes that widened its three sibling engines into clear "
        "failures, which is what makes the pass credible rather than fortunate."
    )

    def recipes(self) -> tuple[Recipe, ...]:
        return (
            Recipe(
                kind=RecipeKind.PIPELINE_STAGE,
                tree="research",
                argv=["{python}", "pipeline.py", "--stage", "market_flow_engine"],
                produces=["outputs/logs/20260824_223938_market_flow_engine.log"],
                est_seconds=65,
                note="Walk-forward Student-t density on an EWMA base with a flow\n"
                "tilt. The C4 screen it rests on is regenerated by `convgap replicate`.",
            ),
        )

    def significance(self) -> EvidenceSet:
        def _screen(era: str) -> Source:
            return Source(
                tree="local",
                artifact="outputs/replication/aggregate_flow_screen.csv",
                locator=f"row cell=C4, era={era}, column t_stat",
                producer="src/convgap/replication/aggregate_flow.py",
            )

        note = (
            "Re-derived by this repository from the pre-registered specification. "
            "The source programme reports t = -4.78 / -2.49 / -2.51 for this cell "
            "but has no stage that computes it; the figures survive only in the "
            "docstring of the module that consumes them. Canonical reading "
            "excludes days with no flow observation; retaining them as NF = 0 "
            "gives -4.90 / -2.84 / -2.60. Both clear both legs of the bar."
        )
        return evidence_set(
            "C4 screen: net inflow at t-2 on next-day |Nifty return|, beyond VIX",
            Evidence(
                -4.83,
                Statistic.T_STAT,
                _screen("FULL"),
                era=Era.FULL,
                n=3178,
                extractor=csv_cell({"cell": "C4", "era": "FULL"}, "t_stat"),
                note=note,
            ),
            Evidence(
                -2.53,
                Statistic.T_STAT,
                _screen("TRAIN"),
                era=Era.TRAIN,
                n=2321,
                extractor=csv_cell({"cell": "C4", "era": "TRAIN"}, "t_stat"),
            ),
            Evidence(
                -2.51,
                Statistic.T_STAT,
                _screen("TEST"),
                era=Era.TEST,
                n=855,
                extractor=csv_cell({"cell": "C4", "era": "TEST"}, "t_stat"),
            ),
        )

    def value(self) -> EvidenceSet:
        return evidence_set(
            "module 21 pre-registered three-leg gate (all legs PASS)",
            Evidence(
                -2.35,
                Statistic.DM_STAT,
                _log("gate leg (a): 'M2 vs M1 FULL DM t = ...', bar t <= -2.0"),
                era=Era.FULL,
                n=2739,
                extractor=_rx(r"\(a\) M2 vs M1 FULL DM t = ([-+\d.]+)"),
            ),
            Evidence(
                -0.0019,
                Statistic.CRPS,
                _log("gate leg (b): mean CRPS advantage x100, TRAIN"),
                era=Era.TRAIN,
                extractor=_rx(r"M2 better in both eras: TRAIN ([-+\d.]+)"),
            ),
            Evidence(
                -0.0004,
                Statistic.CRPS,
                _log("gate leg (b): mean CRPS advantage x100, TEST"),
                era=Era.TEST,
                extractor=_rx(r"M2 better in both eras: TRAIN [-+\d.]+ TEST ([-+\d.]+)"),
            ),
            Evidence(
                0.225,
                Statistic.KUPIEC_P,
                _log("gate leg (c): Kupiec p at the 5% VaR level, full sample"),
                era=Era.FULL,
                extractor=_rx(r"Kupiec p > 0\.01\): p5=([\d.]+)"),
                note="Level, not era. An earlier transcription recorded the two "
                "Kupiec p-values as TRAIN and TEST; they are the 5% and 1% "
                "levels on the full sample.",
            ),
            Evidence(
                0.161,
                Statistic.KUPIEC_P,
                _log("gate leg (c): Kupiec p at the 1% VaR level, full sample"),
                era=Era.FULL,
                extractor=_rx(r"Kupiec p > 0\.01\): p5=[\d.]+ p1=([\d.]+)"),
            ),
        )
